name: kalandra
summary: An apt-mirror2 wrapper targeting airgapped deployments
description: |
  TBF
version: test
base: core24
confinement: strict

parts:
  kalandra:
    plugin: python
    source: .
  config-files:
    plugin: dump
    source: .

apps:
  kalandra:
    command: bin/apt-mirror
    plugs:
      - network

layout:
  /etc/apt:
    bind: $SNAP_COMMON/apt
  /var/spool/apt-mirror:
    bind: $SNAP_COMMON/var/spool/apt-mirror
  /var/log/apt-mirror:
    bind: $SNAP_COMMON/var/log/apt-mirror