name: kalandra
summary: An apt-mirror2 wrapper targeting airgapped deployments
description: |
  TBF
version: test
base: core24
confinement: strict

parts:
  kalandra:
    plugin: python
    source: .
  config-files:
    plugin: dump
    source: .

apps:
  kalandra:
    command: bin/apt-mirror

layout:
  /etc/apt/mirror.list:
    bind-file: $SNAP_COMMON/mirror.list
  /var/spool/apt-mirror:
    bind: $SNAP_COMMON/var/spool/apt-mirror
  /etc/apt/auth.conf.d:
    bind: $SNAP_COMMON/auth.conf.d
  /var/log/apt-mirror:
    bind: $SNAP_COMMON/var/log/apt-mirror