name: kalandra
summary: An apt-mirror2 wrapper with a built-in apache server
description: |
  kalandra is a self-contained apt-mirror2/apache wrapper that can be used to spin up debian repository mirror.
  apt-mirror2 is a python port of apt-mirror, with additional features such a include_source_name to limit repository size.
version: "0.1.0"
base: core24
confinement: strict

apps:
  kalandra:
    command: kalandra
    plugs:
      - network
  apache:
    command: bin/start-apache
    daemon: simple
    install-mode: disable
    restart-condition: always
    plugs:
      - network
      - network-bind

parts:
  kalandra:
    plugin: python
    source: .
    python-packages:
      - uvloop
  apache:
    plugin: nil
    stage-packages:
      - apache2
  launcher:
    plugin: dump
    source: snap/bin
    organize:
      start-apache: bin/start-apache
      export: bin/export
      import: bin/import
  apache2-conf:
    plugin: dump
    source: snap/config
   
layout:
  /etc/apt:
    bind: $SNAP_COMMON/apt
  /var/spool/apt-mirror:
    bind: $SNAP_COMMON/var/spool/apt-mirror
  /var/log/apt-mirror:
    bind: $SNAP_COMMON/var/log/apt-mirror
  /var/www/html:
    bind: $SNAP_COMMON/var/www/html