#!/bin/bash
MIRROR_CONFIG="$SNAP_COMMON/apt/mirror.list"
APACHE_CONFIG="$SNAP_COMMON/conf/apache2.conf"
mkdir -p "$SNAP_COMMON/conf"

if [ ! -f "$MIRROR_CONFIG" ]; then
    cp "$SNAP/config/mirror.list" "$MIRROR_CONFIG"
fi

if [ ! -f "$APACHE_CONFIG" ]; then
    cp "$SNAP/config/apache2.conf" "$APACHE_CONFIG"
fi